name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            set -e

            echo "Changing to project directory..."
            cd ~/distributed-ticket-engine-redis

            echo "Cleaning stale Git locks & force pulling latest code..."
            rm -f .git/refs/remotes/origin/main.lock .git/index.lock .git/FETCH_HEAD || true
            git fetch origin main --prune --force
            git reset --hard origin/main

            echo "Stopping old containers..."
            docker compose down --remove-orphans || true

            echo "Starting Database and Redis first..."
            docker compose up -d --build postgres redis

            echo "Running Prisma migrations in a temporary container..."
            docker compose run --rm -v ./prisma:/app/prisma app ./node_modules/.bin/prisma db push

            echo "Starting Application and Worker services..."
            docker compose up -d app worker

            echo "Deployment completed successfully."